-- MySQL Script generated by MySQL Workbench
-- Fri Jun 28 17:23:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EQUIPES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPES` (
  `id_equipes` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `ano` INT NULL,
  PRIMARY KEY (`id_equipes`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `id_equipes_UNIQUE` (`id_equipes` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PILOTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PILOTOS` (
  `id_pilotos` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `idade` INT NULL,
  `numero` INT NULL,
  `EQUIPES_id_equipes` INT NOT NULL,
  PRIMARY KEY (`id_pilotos`, `EQUIPES_id_equipes`),
  INDEX `fk_PILOTOS_EQUIPES_idx` (`EQUIPES_id_equipes` ASC) VISIBLE,
  CONSTRAINT `fk_PILOTOS_EQUIPES`
    FOREIGN KEY (`EQUIPES_id_equipes`)
    REFERENCES `mydb`.`EQUIPES` (`id_equipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VEICULOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VEICULOS` (
  `idVEICULOS` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `ano` INT NULL,
  `PILOTOS_id_pilotos` INT NOT NULL,
  `PILOTOS_EQUIPES_id_equipes` INT NOT NULL,
  PRIMARY KEY (`PILOTOS_id_pilotos`, `PILOTOS_EQUIPES_id_equipes`, `idVEICULOS`),
  CONSTRAINT `fk_VEICULOS_PILOTOS1`
    FOREIGN KEY (`PILOTOS_id_pilotos` , `PILOTOS_EQUIPES_id_equipes`)
    REFERENCES `mydb`.`PILOTOS` (`id_pilotos` , `EQUIPES_id_equipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PISTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PISTAS` (
  `idPISTAS` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Local` VARCHAR(45) NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`idPISTAS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PISTAS_has_PILOTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PISTAS_has_PILOTOS` (
  `PISTAS_idPISTAS` INT NOT NULL,
  `PILOTOS_id_pilotos` INT NOT NULL,
  `PILOTOS_EQUIPES_id_equipes` INT NOT NULL,
  PRIMARY KEY (`PISTAS_idPISTAS`, `PILOTOS_id_pilotos`, `PILOTOS_EQUIPES_id_equipes`),
  INDEX `fk_PISTAS_has_PILOTOS_PILOTOS1_idx` (`PILOTOS_id_pilotos` ASC, `PILOTOS_EQUIPES_id_equipes` ASC) VISIBLE,
  INDEX `fk_PISTAS_has_PILOTOS_PISTAS1_idx` (`PISTAS_idPISTAS` ASC) VISIBLE,
  CONSTRAINT `fk_PISTAS_has_PILOTOS_PISTAS1`
    FOREIGN KEY (`PISTAS_idPISTAS`)
    REFERENCES `mydb`.`PISTAS` (`idPISTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PISTAS_has_PILOTOS_PILOTOS1`
    FOREIGN KEY (`PILOTOS_id_pilotos` , `PILOTOS_EQUIPES_id_equipes`)
    REFERENCES `mydb`.`PILOTOS` (`id_pilotos` , `EQUIPES_id_equipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESULTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESULTADO` (
  `posicao` INT NOT NULL,
  `PISTAS_has_PILOTOS_PISTAS_idPISTAS` INT NOT NULL,
  `PISTAS_has_PILOTOS_PILOTOS_id_pilotos` INT NOT NULL,
  `PISTAS_has_PILOTOS_PILOTOS_EQUIPES_id_equipes` INT NOT NULL,
  INDEX `fk_RESULTADO_PISTAS_has_PILOTOS1_idx` (`PISTAS_has_PILOTOS_PISTAS_idPISTAS` ASC, `PISTAS_has_PILOTOS_PILOTOS_id_pilotos` ASC, `PISTAS_has_PILOTOS_PILOTOS_EQUIPES_id_equipes` ASC) VISIBLE,
  CONSTRAINT `fk_RESULTADO_PISTAS_has_PILOTOS1`
    FOREIGN KEY (`PISTAS_has_PILOTOS_PISTAS_idPISTAS` , `PISTAS_has_PILOTOS_PILOTOS_id_pilotos` , `PISTAS_has_PILOTOS_PILOTOS_EQUIPES_id_equipes`)
    REFERENCES `mydb`.`PISTAS_has_PILOTOS` (`PISTAS_idPISTAS` , `PILOTOS_id_pilotos` , `PILOTOS_EQUIPES_id_equipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENGENHEIRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENGENHEIRO` (
  `idENGENHEIRO` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `especialidades` VARCHAR(45) NULL,
  `EQUIPES_id_equipes` INT NOT NULL,
  PRIMARY KEY (`idENGENHEIRO`),
  INDEX `fk_ENGENHEIRO_EQUIPES1_idx` (`EQUIPES_id_equipes` ASC) VISIBLE,
  CONSTRAINT `fk_ENGENHEIRO_EQUIPES1`
    FOREIGN KEY (`EQUIPES_id_equipes`)
    REFERENCES `mydb`.`EQUIPES` (`id_equipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CHEFE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CHEFE` (
  `idCHEFE` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `funcao` VARCHAR(45) NULL,
  `EQUIPES_id_equipes` INT NOT NULL,
  PRIMARY KEY (`idCHEFE`),
  INDEX `fk_CHEFE_EQUIPES1_idx` (`EQUIPES_id_equipes` ASC) VISIBLE,
  CONSTRAINT `fk_CHEFE_EQUIPES1`
    FOREIGN KEY (`EQUIPES_id_equipes`)
    REFERENCES `mydb`.`EQUIPES` (`id_equipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
